openapi: 3.0.2
info:
  title: Sample API
  description: A description of the API
  version: 1.0.0

servers:
  - url: http://localhost/v1 # note that 'v1' is not appended to paths, only for documentation!

paths:
  /api:
    get:
      summary: Returns a list of entities.
      operationId: return.entities
      description: | # pipe gives us multi-line support
        Describes the API - this is just a silly example
      responses:
        200:
          description: A JSON array of entities available
          headers:
            X-Response-Time:
              $ref: '#/components/headers/X-Response-Time'
            Limit-Entities:
              description: Control the maximum amount of entities returned
              required: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entities'
    post:
      summary: Add entity
      operationId: add.entity
      description: |
        We can add entities to our API as well!
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        200:
          description: |
            Successful addition of an entity
          headers:
            'X-Response-Time':
              $ref: '#/components/headers/X-Response-Time'
          content:
            application/json:
              schema:
                type: string

components:
  headers:
    X-Response-Time:
      description: The measured server response time
      schema:
        type: string
      example: 13ms

  schemas:
    Entities:
      type: array
      description: A list of entities
      deprecated: false
      items:
        $ref: '#/components/schemas/Entity'
    Entity:
      type: object
      description: An entity
      deprecated: false
      required:
        - name
        - age
      properties:
        name:
          type: string
        gender:
          type: string
        age:
          type: integer
